const items = [
    { name: 'Ahri', src: 'img/ahri.png', lane: 'Mid' },
    { name: 'Alistar', src: 'img/alistar.png', lane: 'Suporte' },
    { name: 'Azir', src: 'img/azir.png', lane: 'Mid' },
    { name: 'Brand', src: 'img/brand.png', lane: 'Mid | Suporte' },
    { name: 'Corki', src: 'img/corki.png', lane: 'Mid | ADC' },
    { name: 'Darius', src: 'img/darius.png', lane: 'Top' },
    { name: 'Draven', src: 'img/draven.png', lane: 'ADC' },
    { name: 'Garen', src: 'img/garen.png', lane: 'Top' },
    { name: 'Lee Sin', src: 'img/leesin.png', lane: 'Jungle' },
    { name: 'Lulu', src: 'img/lulu.png', lane: 'Suporte' },
    { name: 'Nasus', src: 'img/nasus.png', lane: 'Top' },
    { name: 'Shyvana', src: 'img/shyvana.png', lane: 'Top | Jungle' },
    { name: 'Smolder', src: 'img/smolder.png', lane: 'Top | Mid | ADC' },
    { name: 'Sona', src: 'img/sona.png', lane: 'Suporte' },
    { name: 'Teemo', src: 'img/teemo.png', lane: 'Top | Mid' },
    { name: 'Thresh', src: 'img/thresh.png', lane: 'Suporte' },
    { name: 'Tristana', src: 'img/tristana.png', lane: 'Mid | ADC' },
    { name: 'Vayne', src: 'img/vayne.png', lane: 'ADC' },
    { name: 'Warwick', src: 'img/warwick.png', lane: 'Jungle' },
    { name: 'Yasuo', src: 'img/yasuo.png', lane: 'Top | Mid' },
    { name: 'Zac', src: 'img/zac.png', lane: 'Jungle' },
    { name: 'Zed', src: 'img/zed.png', lane: 'Top | Mid' }
]
